"""Read-only data access for the Streamlit inbox."""

from __future__ import annotations

import json
from collections.abc import Generator
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path

import duckdb


#: The 5 review states mandated by the brief. Order matters for the selectbox.
VALID_REVIEW_STATES = (
    "nuevo",
    "en revisión",
    "requiere evidencia",
    "aprobado como borrador",
    "descartado",
)


class ScoreUnavailableError(RuntimeError):
    """The TAR-008 scoring output is not available for the inbox."""


@dataclass(frozen=True)
class InboxGroup:
    """A scored news group ready for the priority inbox."""

    grupo_id: str
    titulo_representativo: str
    n_noticias: int
    n_procedencias: int
    fecha_max: object
    corroboracion: int
    es_repeticion: bool
    tema: str
    R: float
    I: float  # noqa: E741 - TAR-008 contract name
    U: float
    N: float
    E: float
    puntaje: float
    prioridad: str
    estado_evidencia: str
    version_reglas: str
    motivos: str
    contexto_oficial: str | None
    evento_usgs_id: str | None


@dataclass(frozen=True)
class GroupFicha:
    """The real TAR-009 ficha for a group: draft, citations and review state.

    ``estado_revision`` and ``tipo_respuesta`` come from the table's own
    columns, which are the authoritative, updatable source (see
    ``persist_ficha_review_state``). The remaining fields are parsed from the
    ``ficha`` JSON blob produced at generation time.
    """

    id_caso: str
    estado_revision: str
    tipo_respuesta: str  # respuesta | abstencion | contradiccion
    borrador: str | None
    citas: list[tuple[str, str]]  # (id_evidencia, campo)
    afirmaciones: list[str]
    motivo_abstencion: str | None
    generado_en: datetime | None


def fetch_group_ficha(
    motor_path: str | Path, signals_path: str | Path, grupo_id: str
) -> GroupFicha | None:
    """Return the real TAR-009 ficha for ``grupo_id``, or ``None`` if absent.

    Reads the read-only `fichas` table (generated by `motor/generar.py`,
    TAR-022, pending Ollama). Returns ``None`` both when the table does not
    exist yet and when no ficha has been generated for this group, so the
    caller can show an honest "borrador no generado" message either way.
    ``signals_path`` is accepted for signature symmetry with the other
    readers; reading `fichas` does not require the signals attachment.
    """

    del signals_path
    try:
        with duckdb.connect(str(motor_path), read_only=True) as connection:
            row = connection.sql(
                "SELECT id_caso, estado_revision, tipo_respuesta, ficha, generado_en "
                "FROM fichas WHERE id_caso = ?",
                params=[grupo_id],
            ).fetchone()
    except duckdb.CatalogException:
        return None

    if row is None:
        return None

    id_caso, estado_revision, tipo_respuesta, ficha_json, generado_en = row
    payload = json.loads(ficha_json) if ficha_json else {}
    citas = [
        (cita["id_evidencia"], cita["campo"]) for cita in payload.get("citas", [])
    ]

    return GroupFicha(
        id_caso=id_caso,
        estado_revision=estado_revision,
        tipo_respuesta=tipo_respuesta,
        borrador=payload.get("borrador"),
        citas=citas,
        afirmaciones=[
            str(item.get("texto", "")) if isinstance(item, dict) else str(item)
            for item in payload.get("afirmaciones", [])
        ],
        motivo_abstencion=payload.get("motivo_abstencion"),
        generado_en=generado_en,
    )


def persist_ficha_review_state(
    motor_path: str | Path, grupo_id: str, new_state: str
) -> None:
    """Persist the editor's review decision for a real ficha, if it exists.

    Uses a short-lived read-write connection and never creates the `fichas`
    table: pipeline generation (TAR-022) remains the only writer of its
    structural columns, this only updates `estado_revision`.
    """

    if new_state not in VALID_REVIEW_STATES:
        raise ValueError(f"Estado de revisión inválido: {new_state!r}")

    try:
        with duckdb.connect(str(motor_path), read_only=False) as connection:
            connection.execute(
                "UPDATE fichas SET estado_revision = ? WHERE id_caso = ?",
                [new_state, grupo_id],
            )
    except duckdb.CatalogException:
        return


@dataclass(frozen=True)
class ChatResponse:
    """A mock or future LLM response with explicit citations."""

    respuesta: str
    abstencion: bool
    citas: list[str]


def ask_group_question(grupo_id: str, question: str) -> ChatResponse:
    """Mock CU-04: Returns a cited response or abstention.

    Pending Guille's TAR-009 LLM generation integration.
    """

    question_lower = question.lower()
    if "cuándo" in question_lower or "cuando" in question_lower or "fecha" in question_lower:
        return ChatResponse(
            respuesta="El evento ocurrió a principios de enero de 2026, según reportan múltiples fuentes locales.",
            abstencion=False,
            citas=["E-1", "E-2"]
        )
    if "quién" in question_lower or "quien" in question_lower:
        return ChatResponse(
            respuesta="El anuncio fue realizado por representantes del sector oficial.",
            abstencion=False,
            citas=["E-4"]
        )
    return ChatResponse(
        respuesta="No hay evidencia suficiente en este grupo de noticias para responder a esa consulta.",
        abstencion=True,
        citas=[]
    )


@dataclass(frozen=True)
class EvidenceRow:
    """A read-only group member and its source metadata."""

    id_noticia: str
    titulo: str | None
    url: str | None
    medio: str | None
    procedencia: str | None
    fecha_publicacion: datetime | None
    fecha_deteccion: datetime | None
    similitud_al_centroide: float | None


@contextmanager
def open_inbox_repository(
    motor_path: str | Path, signals_path: str | Path
) -> Generator[duckdb.DuckDBPyConnection, None, None]:
    """Open the motor repository and its signals dependency without write access."""

    connection = duckdb.connect(str(motor_path), read_only=True)
    try:
        connection.sql(_read_only_attach_query(signals_path))
        yield connection
    finally:
        connection.close()


def _read_only_attach_query(signals_path: str | Path) -> str:
    """Build the escaped ATTACH statement required by DuckDB's grammar."""

    escaped_path = str(signals_path).replace("'", "''")
    return "ATTACH '__SIGNALS_PATH__' AS senales (READ_ONLY)".replace(
        "__SIGNALS_PATH__", escaped_path
    )


def fetch_inbox_groups(
    motor_path: str | Path,
    signals_path: str | Path,
    *,
    topic: str | None = None,
    start_date: date | None = None,
    end_date: date | None = None,
    limit: int = 50,
) -> list[InboxGroup]:
    """Return TAR-008-scored, non-``otros`` groups in priority order."""

    if limit < 1:
        raise ValueError("limit must be at least 1")

    query = """
        SELECT
            g.grupo_id, g.titulo_representativo, g.n_noticias, g.n_procedencias,
            g.fecha_max, g.corroboracion, g.es_repeticion, p.tema,
            p.R, p.I, p.U, p.N, p.E, p.puntaje, p.prioridad,
            p.estado_evidencia, p.version_reglas, p.motivos,
            p.contexto_oficial, p.evento_usgs_id
        FROM grupos AS g
        JOIN puntaje AS p ON p.grupo_id = g.grupo_id
        WHERE p.tema <> 'otros'
            AND (? IS NULL OR p.tema = ?)
            AND (? IS NULL OR CAST(g.fecha_max AS DATE) >= ?)
            AND (? IS NULL OR CAST(g.fecha_max AS DATE) <= ?)
        ORDER BY p.puntaje DESC, p.U DESC, g.grupo_id ASC
        LIMIT ?
    """
    parameters = [topic, topic, start_date, start_date, end_date, end_date, limit]
    try:
        with open_inbox_repository(motor_path, signals_path) as connection:
            rows = connection.sql(query, params=parameters).fetchall()
    except duckdb.CatalogException as error:
        raise ScoreUnavailableError(
            "No hay puntajes TAR-008 disponibles. Ejecute el motor de puntaje."
        ) from error

    return [InboxGroup(*row) for row in rows]


def fetch_group_evidence(
    motor_path: str | Path, signals_path: str | Path, grupo_id: str
) -> list[EvidenceRow]:
    """Return group members in chronological editorial order.

    Publication dates remain null when the source does not provide one; detection
    dates are a separate metadata field and only order otherwise-undated rows.
    """

    query = """
        SELECT
            n.id_noticia, n.titulo, n.url, n.medio, gn.procedencia,
            n.fecha_publicacion, n.fecha_deteccion, gn.similitud_al_centroide
        FROM grupo_noticias AS gn
        JOIN senales.noticias AS n ON n.id_noticia = gn.id_noticia
        WHERE gn.grupo_id = ?
        ORDER BY
            n.fecha_publicacion ASC NULLS LAST,
            n.fecha_deteccion ASC NULLS LAST,
            n.id_noticia ASC
    """
    with open_inbox_repository(motor_path, signals_path) as connection:
        rows = connection.sql(query, params=[grupo_id]).fetchall()

    return [EvidenceRow(*row) for row in rows]


def fetch_inbox_filter_options(
    motor_path: str | Path, signals_path: str | Path
) -> tuple[list[str], date | None, date | None]:
    """Return uncapped topics and date bounds for query-level inbox filters.

    Topics and date bounds are computed in SQL (DISTINCT / MIN / MAX) instead
    of fetching every row, since only the aggregates are needed.
    """

    where_clause = "WHERE p.tema <> 'otros' AND g.fecha_max IS NOT NULL"
    topics_query = f"""
        SELECT DISTINCT p.tema
        FROM grupos AS g
        JOIN puntaje AS p ON p.grupo_id = g.grupo_id
        {where_clause}
        ORDER BY p.tema
    """
    bounds_query = f"""
        SELECT MIN(CAST(g.fecha_max AS DATE)), MAX(CAST(g.fecha_max AS DATE))
        FROM grupos AS g
        JOIN puntaje AS p ON p.grupo_id = g.grupo_id
        {where_clause}
    """
    try:
        with open_inbox_repository(motor_path, signals_path) as connection:
            topics = [row[0] for row in connection.sql(topics_query).fetchall()]
            bounds = connection.sql(bounds_query).fetchone()
    except duckdb.CatalogException as error:
        raise ScoreUnavailableError(
            "No hay puntajes TAR-008 disponibles. Ejecute el motor de puntaje."
        ) from error

    if not topics:
        with open_inbox_repository(motor_path, signals_path) as connection:
            availability = connection.sql(
                "SELECT EXISTS(SELECT 1 FROM grupos), EXISTS(SELECT 1 FROM puntaje)"
            ).fetchone()
        if availability is None:
            raise ScoreUnavailableError("No se pudo comprobar el motor de puntaje.")
        has_groups, has_scores = availability
        if has_groups and not has_scores:
            raise ScoreUnavailableError(
                "No hay puntajes TAR-008 disponibles. Ejecute el motor de puntaje."
            )

    min_date, max_date = bounds if bounds else (None, None)
    return topics, min_date, max_date
